# Generated by Django 4.1.7 on 2023-04-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discout',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
